### ISSUE TITLE
Control center doesn't show my environments on Ubuntu.

### ISSUE THREAD

**Issue by AlinaPenkina** [subutai-io/control-center#777]
Only after rebooting of CC it shows my environment.
![image](https://user-images.githubusercontent.com/34295807/38071820-5770e5f4-3345-11e8-852e-20b35b9f1034.png)

**Comment by Erkin97** [comment]
* CC gets information from Bazaar, it sometimes this list was not refreshed yet.

**Comment by AlinaPenkina** [comment]
![image](https://user-images.githubusercontent.com/34295807/39080444-8b7d66ac-4550-11e8-8441-782ff54353c8.png)
![image](https://user-images.githubusercontent.com/34295807/39080451-a2dd48e4-4550-11e8-9472-d5d08138d17e.png)

**Comment by AlinaPenkina** [comment]
I still face such kind of problems on ubuntu.

**Comment by AlinaPenkina** [comment]
[logs_09.txt](https://github.com/subutai-io/control-center/files/1934162/logs_09.txt)
[logs_10.txt](https://github.com/subutai-io/control-center/files/1934163/logs_10.txt)

**Comment by ibragim13kz** [comment]
Fixed in Master.

**Comment by AlinaPenkina** [comment]
Done.

**Comment by AlinaPenkina** [comment]
We still face this problem on Ubuntu(after some time CC doesn't show current envs.)

**Comment by ibragim13kz** [comment]
Faced same bug on Ubuntu after PC sleep. 
[logs_10.txt](https://github.com/subutai-io/control-center/files/1960058/logs_10.txt)
[logs_11.txt](https://github.com/subutai-io/control-center/files/1960059/logs_11.txt)
[Uploading logs_12.txt…]()
[Uploading logs_13.txt…]()
[Uploading logs_14.txt…]()
[Uploading logs_15.txt…]()

**Comment by ibragim13kz** [comment]
Faced same bug on Ubuntu after PC sleep.
[logs_15.txt](https://github.com/subutai-io/control-center/files/1960294/logs_15.txt)
[logs_14.txt](https://github.com/subutai-io/control-center/files/1960295/logs_14.txt)
[logs_13.txt](https://github.com/subutai-io/control-center/files/1960296/logs_13.txt)
[logs_12.txt](https://github.com/subutai-io/control-center/files/1960297/logs_12.txt)
[logs_11.txt](https://github.com/subutai-io/control-center/files/1960298/logs_11.txt)
[logs_10.txt](https://github.com/subutai-io/control-center/files/1960299/logs_10.txt)

**Comment by AlinaPenkina** [comment]
Fixed.

**Comment by ibragim13kz** [comment]
Fixed in Prod.
