### ISSUE TITLE
Menu screws up after a while

### ISSUE THREAD

**Issue by lbthomsen** [subutai-io/control-center#819]
Debian/KDE - menu screws up after a day or so:

![image](https://user-images.githubusercontent.com/2730860/38594689-1b74563c-3d7a-11e8-9893-5642681329bd.png)

**Comment by AlinaPenkina** [comment]
[logs_11.txt](https://github.com/subutai-io/control-center/files/1914015/logs_11.txt)

**Comment by Erkin97** [comment]
* I found critical sections in update tray menu.
* Mutexes will fix it

**Comment by Erkin97** [comment]
* added mutexes
* need to test more

**Comment by ibragim13kz** [comment]
Fixed. Reproduced on Debian.

**Comment by AlinaPenkina** [comment]
done.

**Comment by lbthomsen** [comment]
![bug](https://user-images.githubusercontent.com/2730860/40397134-882717b0-5e63-11e8-9cd8-1dcc716b7433.png)

Just now on prod - so this bug is still there!

**Comment by ibragim13kz** [comment]
Fixed in Master.

**Comment by ibragim13kz** [comment]
Fixed in Prod.
